@Library("shared-library") _
pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                script {
                    buildManager()
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    sonarQubeManager()
                }
            }
        }

        stage('Verify Build') {
            steps {
                sh 'ls -l target/'
            }
        }

        stage('UnitTest') {
            steps {
                unittestManager()
            }
        }

        stage('IntegrationTest') {
            steps {
                integrationtestManager()
            }
        }

        stage('Docker Build and Push') {
            steps {
                script {
                    dockerManager()
                }
            }
        }

        stage('Publish to JFrog Artifactory') {
            steps {
                script {
                    jfrogManager()
                }
            }
        }

        stage('Deploy to EC2') {
            steps {
                deployManager()
            }
        }
    }
}
